# Generated by Django 4.0 on 2022-01-05 20:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.address')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_show', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.amenity', verbose_name='Amenity for Reservation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.profile', verbose_name='Profile for Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceProfileRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Authorized User', 'Authorized User'), ('Member', 'Member')], default='Member', max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of', to='mgmt.place', verbose_name='Place in the relationship')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_profile_of', to='mgmt.profile', verbose_name='Profile in the relationship')),
            ],
            options={
                'verbose_name': 'Place Profile Relationship',
                'verbose_name_plural': 'Place Profile Relationships',
            },
        ),
        migrations.CreateModel(
            name='AmenityProfileRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('0', 'Owner'), ('1', 'Manager'), ('2', 'Supervisor'), ('3', 'Staff'), ('4', 'Authorized User'), ('5', 'Member')], default='5', max_length=100)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_of', to='mgmt.amenity', verbose_name='Amenity in the relationship')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_profile_of', to='mgmt.profile', verbose_name='Profile in the relationship')),
            ],
            options={
                'verbose_name': 'Amenity Profile Relationship',
                'verbose_name_plural': 'Amenity Profile Relationships',
            },
        ),
        migrations.AddField(
            model_name='amenity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mgmt.place'),
        ),
    ]
