# Generated by Django 4.0 on 2021-12-26 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='duration_slot',
            field=models.DurationField(default=datetime.timedelta(seconds=68400)),
        ),
    ]
