# Generated by Django 4.0 on 2022-01-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mgmt.place'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.place', verbose_name='Place in the relationship')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.profile', verbose_name='Profile in the relationship')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
