# Generated by Django 4.0 on 2022-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='timeslots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
