# Generated by Django 4.0 on 2022-01-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_alter_placeprofilerelationship_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mgmt.place'),
        ),
    ]
