# Generated by Django 4.0 on 2021-12-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_amenity_duration_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='duration_slot',
            field=models.TimeField(default=None),
        ),
    ]
