# Generated by Django 4.0 on 2022-01-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_alter_amenity_place_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.place'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.profile'),
        ),
    ]
