# Generated by Django 4.0 on 2022-01-09 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0003_reservation_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='amenityprofilerelationship',
            options={'ordering': ('date_created',), 'verbose_name': 'Amenity Profile Relationship', 'verbose_name_plural': 'Amenity Profile Relationships'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='placeprofilerelationship',
            options={'ordering': ('date_created',), 'verbose_name': 'Place Profile Relationship', 'verbose_name_plural': 'Place Profile Relationships'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='address',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenityprofilerelationship',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeprofilerelationship',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='mgmt.place'),
        ),
    ]
