# Generated by Django 4.0 on 2022-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alias',
            field=models.CharField(default='<django.db.models.fields.EmailField> <django.db.models.fields.CharField>', max_length=200, null=True),
        ),
    ]
