# Generated by Django 4.0 on 2022-03-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
