# Generated by Django 4.0 on 2022-03-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_place_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='placeprofilerelationship',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.place', verbose_name='Place in the relationship'),
        ),
        migrations.AlterField(
            model_name='placeprofilerelationship',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile', verbose_name='Profile in the relationship'),
        ),
    ]
