# Generated by Django 4.0 on 2022-05-19 07:46

from django.db import migrations, models
import siteApp.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=siteApp.utilities.user_upload_directory_path),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=siteApp.utilities.user_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=siteApp.utilities.user_upload_directory_path),
        ),
    ]
