# Generated by Django 4.0 on 2022-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_alter_amenity_image_alter_place_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='backup_random_image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1594310814895-0a96c1b180be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8bmF0dXJlLXdhbGxwYXBlcix0cm9waWNhbC12ZWdldGF0aW9ufHx8fHx8MTY1Mzg5NzUwOA&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080'),
            preserve_default=False,
        ),
    ]
