# Generated by Django 4.0 on 2022-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_amenity_backup_random_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='backup_random_image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1542028457068-736edcec3ab5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8bmF0dXJlLXdhbGxwYXBlcix0cm9waWNhbC12ZWdldGF0aW9ufHx8fHx8MTY1Mzg5ODE4Mg&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080'),
            preserve_default=False,
        ),
    ]
