# Generated by Django 4.0 on 2022-05-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0005_place_backup_random_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='backup_random_image_url',
            new_name='backup_image_url',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='backup_random_image_url',
            new_name='backup_image_url',
        ),
    ]
